In [1]:
#tweeter sentiment analysis

import pandas as pd
import numpy as np

In [2]:
#input data
test=pd.read_csv("/Users/suraj/Downloads/CSS/test_tweets_anuFYb8.csv")
test.head()

id                                              tweet
0  31963  #studiolife #aislife #requires #passion #dedic...
1  31964   @user #white #supremacists want everyone to s...
2  31965  safe ways to heal your #acne!!    #altwaystohe...
3  31966  is the hp and the cursed child book up for res...
4  31967    3rd #bihday to my amazing, hilarious #nephew...

In [3]:
train=pd.read_csv("/Users/suraj/Downloads/CSS/train_E6oV3lV.csv")
train.head()

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31962 entries, 0 to 31961
Data columns (total 3 columns):
id       31962 non-null int64
label    31962 non-null int64
tweet    31962 non-null object
dtypes: int64(2), object(1)
memory usage: 749.2+ KB


In [5]:
train.describe()

id         label
count  31962.000000  31962.000000
mean   15981.500000      0.070146
std     9226.778988      0.255397
min        1.000000      0.000000
25%     7991.250000      0.000000
50%    15981.500000      0.000000
75%    23971.750000      0.000000
max    31962.000000      1.000000

In [6]:
train['label'].value_counts()

0    29720
1     2242
Name: label, dtype: int64

In [7]:
test.head()

id                                              tweet
0  31963  #studiolife #aislife #requires #passion #dedic...
1  31964   @user #white #supremacists want everyone to s...
2  31965  safe ways to heal your #acne!!    #altwaystohe...
3  31966  is the hp and the cursed child book up for res...
4  31967    3rd #bihday to my amazing, hilarious #nephew...

In [8]:
#cleaning data
def drop_features(features,data):
    data.drop(features,inplace=True,axis=1)

In [9]:
import re

In [10]:
def process_tweet(tweet):
    return " ".join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])","",tweet.lower()).split())

In [11]:
train['processed_tweets']=train['tweet'].apply(process_tweet)

In [12]:
drop_features(['id','tweet'],train)

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(train["processed_tweets"], train["label"], test_size = 0.2, random_state = 42)

In [14]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer
count_vect=CountVectorizer(stop_words='english')
transformer = TfidfTransformer(norm='l2',sublinear_tf=True)

In [15]:
x_train_counts = count_vect.fit_transform(x_train)
x_train_tfidf = transformer.fit_transform(x_train_counts)

In [16]:
print(x_train_counts.shape)
print(x_train_tfidf.shape)

(25569, 35626)
(25569, 35626)


In [17]:
x_train_counts

<25569x35626 sparse matrix of type '<class 'numpy.int64'>'
	with 178738 stored elements in Compressed Sparse Row format>

In [18]:
x_test_counts = count_vect.transform(x_test)
x_test_tfidf = transformer.transform(x_test_counts)

In [19]:
print(x_test_counts.shape)
print(x_test_tfidf.shape)

(6393, 35626)
(6393, 35626)


In [20]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=500)
model.fit(x_train_tfidf,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [21]:
predictions = model.predict(x_test_tfidf)
predictions

array([0, 0, 0, ..., 0, 0, 1])

In [22]:
from sklearn.metrics import confusion_matrix,f1_score
confusion_matrix(y_test,predictions)

array([[5900,   37],
       [ 217,  239]])

In [23]:
f1_score(y_test,predictions)

0.6530054644808744

In [24]:
predictions

array([0, 0, 0, ..., 0, 0, 1])

In [25]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17197 entries, 0 to 17196
Data columns (total 2 columns):
id       17197 non-null int64
tweet    17197 non-null object
dtypes: int64(1), object(1)
memory usage: 268.8+ KB


In [26]:
test['processed_tweet'] = test['tweet'].apply(process_tweet)

In [27]:
test.head(10)

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   
5  31968                        choose to be   :) #momtips    
6  31969  something inside me dies 💦💿✨  eyes nes...   
7  31970  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...   
8  31971   @user @user @user i will never understand why...   
9  31972  #delicious   #food #lovelife #capetown mannaep...   

                                     processed_tweet  
0  studiolife aislife requires passion dedication...  
1  white supremacists want everyone to see the ne...  
2  safe ways to heal your acne altwaystoheal heal...  
3  is the hp and the cursed child book up for res...  
4  3rd bihday to my amazing hilarious nephew eli ...  
5                               choose to be momtips  
6  something inside me dies eyes ness smokeyeyes ...  
7          finishedtattooinkedinkloveit thanksaleeee  
8  i will never understand why my dad left me whe...  
9  delicious food lovelife capetown mannaepicure ...

In [28]:
drop_features(['tweet'],test)

In [29]:
train_counts = count_vect.fit_transform(train['processed_tweets'])
test_counts = count_vect.transform(test['processed_tweet'])

In [30]:
print(train_counts.shape)
print(test_counts.shape)

(31962, 41120)
(17197, 41120)


In [31]:
train_tfidf = transformer.fit_transform(train_counts)
test_tfidf = transformer.transform(test_counts)

In [32]:
print(train_tfidf)
print(test_tfidf)

  (0, 32246)	0.39839876992441914
  (0, 31380)	0.29725517140593477
  (0, 20375)	0.2686010656701497
  (0, 13215)	0.2704705438349192
  (0, 11613)	0.4690951114194447
  (0, 11612)	0.4512846078109024
  (0, 11293)	0.42884602694787793
  (1, 39656)	0.3319718542867811
  (1, 38432)	0.3415354402504949
  (1, 38287)	0.2200308394683182
  (1, 36106)	0.18855403022770365
  (1, 27541)	0.3319718542867811
  (1, 26329)	0.2684917988867741
  (1, 22440)	0.3184927369277078
  (1, 15219)	0.3415354402504949
  (1, 11117)	0.16003919703389238
  (1, 10703)	0.35501455760956824
  (1, 9169)	0.28588644764120674
  (1, 7081)	0.23542697000198134
  (2, 22645)	0.8806924395668028
  (2, 4977)	0.473688533627186
  (3, 38245)	0.5594340734725757
  (3, 36699)	0.46342858502788675
  (3, 24013)	0.577130592241611
  (3, 22059)	0.37307873634901645
  :	:
  (31958, 32535)	0.23080125446547614
  (31958, 25626)	0.3037357152731366
  (31958, 22869)	0.3248185025190918
  (31958, 21500)	0.13570366845362603
  (31958, 18484)	0.2758657864941755
  (3195

In [33]:
model.fit(train_tfidf,train['label'])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [34]:
predictions = model.predict(test_tfidf)

In [35]:
final_result = pd.DataFrame({'id':test['id'],'label':predictions})
final_result.to_csv('Output.csv',index=False)

In [36]:
final_result.head()

id  label
0  31963      0
1  31964      1
2  31965      0
3  31966      0
4  31967      0